Fixed README for "Option '--semver' does not take a value."
After following the documentation to disable semantic versioning, the command
call failed with:

$ vinnie --semver=False bump
Error: Option '--semver' does not take a value.

This branch proposes changes to the README so `--no-semver` is used instead.